config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  resources :listings do
    post 'filter', on: :collection
    resources :offers, only: [:create]
  end

  devise_scope :users do
    get "users/:id/offers" => "offers#index", as: :offers
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/listing.rb
class Listing < ApplicationRecord
  belongs_to :user
  has_many :offers, dependent: :destroy
  has_many_attached :photos
  include PgSearch::Model
  pg_search_scope :search_by_name_and_description,
    against: [ :name, :description, :condition ],
    using: {
      tsearch: { prefix: true }
    }
  validates :name, :price_per_day, :equipment_type, :photos, presence: true

end

app/models/offer.rb
class Offer < ApplicationRecord
  belongs_to :listing
  belongs_to :user
  validates :start_date, presence: true
  validates :end_date, presence: true, comparison: { greater_than_or_equal_to: :start_date }
  validate :start_date_in_future, unless: -> { start_date.nil? }

  private

  def start_date_in_future
    if start_date < Date.today
      errors.add(:start_date, "can't be in the past")
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :first_name, :last_name, :location, presence: true
  has_many :listings, dependent: :destroy
  has_many :offers, dependent: :destroy
  has_one_attached :photo
  # has_many :photos
  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :location, :photo])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :location, :photo])
  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  skip_before_action :authenticate_user!, only: :index

  def index
    if params[:query].present?
      @listings = Listing.search_by_name_and_description(params[:query])
    else
      @listings = Listing.all
    end
  end

  def filter
    filters = params[:filters] || []
    @filtered_ids = Listing.where(condition: filters).pluck(:id)

    respond_to do |format|
      format.json { render json: @filtered_ids }
    end
  end

  def show
    @listing = set_listing
    @offer = Offer.new
    @markers = geocode(@listing)
  end

  def new
    @listing = Listing.new
  end

  def create
    @listing = Listing.new(listing_params)
    @listing.user = current_user
    if @listing.save
      redirect_to listing_path(@listing)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @listing = set_listing
  end

  def update
    @listing = set_listing
    @listing.update(listing_params)
    redirect_to listing_path(@listing)
  end

  def destroy
    @listing = set_listing
    @listing.destroy
    redirect_to offers_path(current_user)
  end

  private

  def listing_params
    params.require(:listing).permit(
      :name,
      :equipment_type,
      :price_per_day,
      :size,
      :condition,
      :brand,
      :gender,
      :description,
      photos: []
    )
  end

  # Geocoding on index for test
  def geocode(listing)
    # The `geocoded` scope filters only flats with coordinates
    @markers =
      [{
        lat: listing.user.latitude,
        lng: listing.user.longitude,
        info_window_html: render_to_string(partial: "info_window", locals: {listing: listing}),
        marker_html: render_to_string(partial: "marker", locals: {listing: listing})
      }]
  end

  def set_listing
    @listing = Listing.find(params[:id])
  end
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  before_action :set_listing, only: [:create]

  def create
    @offer = Offer.new(offer_params)
    @offer.listing = @listing
    @offer.user = current_user
    @offer.offer_status = "pending"
    if @offer.save
      redirect_to offers_path(current_user)
    else
      render "listings/show", status: 422
    end
  end

  def index
    @user = current_user
    @outgoing_offers = @user.offers.sort_by(&:start_date)
    @listings = @user.listings
  end

  private

  def offer_params
    params.require(:offer).permit(:start_date, :end_date, :message)
  end

  def set_listing
    @listing = Listing.find(params[:listing_id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SlopeRentals</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>
    <div class="content"><%= yield %></div>
    <%= render "shared/footer"%>
  </body>
</html>

app/views/listings/_filters.html.erb
<div data-controller="filter" class="filter_sidebar">
  <button class="filter_button btn" data-filter-target="button" data-action="click->filter#expandFilters"><i class="fa-solid fa-sliders fa-l"></i> Filter</button>
    <div class="filters d-none filter py-3 my-3" data-filter-target="filters">
      <div class="d-flex filter-header justify-content-between">
        <h3>Filters</h3>
        <button data-action="click->filter#closeFilters" class="btn filter_x" do><i class="fa-solid fa-x"></i></button>
      </div>
      <h5 class="filter_heading">Item type</h5>
      <div class="filter_sub d-flex align-items-center">
        <ul>
          <li>
            <label for="Item type">Snowboard</label>
            <input type="checkbox" name="itemtype" value="Snowboard">
          </li>
          <li>
            <label for="Item type">Helmet</label>
            <input type="checkbox" name="itemtype" value="Helmet">
          </li>
          <li>
            <label for="Item type">Gloves</label>
            <input type="checkbox" name="itemtype" value="Gloves">
          </li>
          <li>
            <label for="Item type">Skis</label>
            <input type="checkbox" name="itemtype" value="Skis">
          </li>
          <li>
            <label for="Item type">Goggles</label>
            <input type="checkbox" name="itemtype" value="Goggles">
          </li>
          <li>
            <label for="Item type">Boots</label>
            <input type="checkbox" name="itemtype" value="Boots">
          </li>
        </ul>
      </div>

      <h5 class="filter_heading">Condition</h5>
      <div class="filter_sub d-flex align-items-center">
        <ul>
          <li>
            <label for="Condition">Brand new</label>
            <input type="checkbox" name="condition" value="Brand new" data-results-filter-target="checkboxCondition" data-action="click->results-filter#filterIndex">
          </li>
          <li>
            <label for="Condition">Excellent</label>
            <input type="checkbox" name="condition" value="Excellent" data-results-filter-target="checkboxCondition" data-action="click->results-filter#filterIndex">
          </li>
          <li>
            <label for="Condition">Very good</label>
            <input type="checkbox" name="condition" value="Very good" data-results-filter-target="checkboxCondition" data-action="click->results-filter#filterIndex">
          </li>
          <li>
            <label for="Condition">Good</label>
            <input type="checkbox" name="condition" value="Good" data-results-filter-target="checkboxCondition" data-action="click->results-filter#filterIndex">
          </li>
          <li>
            <label for="Condition">Well worn</label>
            <input type="checkbox" name="condition" value="Well worn" data-results-filter-target="checkboxCondition" data-action="click->results-filter#filterIndex">
          </li>
        </ul>
      </div>


    </div>
</div>

app/views/listings/_info_window.html.erb
<h4><%= listing.name %></h4>
<p><%= cl_image_tag listing.photos.first.key, height: 150, width: 220, crop: :fill %></p>
<p class="mb-0"> <strong>Equipment: </strong> <%= listing.equipment_type %></p>
<p class="mb-1"> <strong>Price per day: </strong> £<%= listing.price_per_day %></p>

app/views/listings/_listing_card.html.erb
<div class="card-category">
  <%= cl_image_tag listing.photos.first.key %>
  <div class="card-infos-container">
    <div>
      <h4><%= listing.name %></h4>
    </div>
    <div class="card-infos">
      <p class="card-infos-price">£<%= listing.price_per_day %> per day </p>
      <div class="seller">
        <p><%= listing.user.first_name %> <%= listing.user.last_name.first %></p>
        <% if listing.user.photo.key? %>
          <%= cl_image_tag listing.user.photo.key%>
        <% else%>
          <img src=<%= image_path("unknown.png") %> class="card-seller" alt="User picture" width="50" height="50">
        <% end %>
      </div>

    </div>
  </div>
</div>

app/views/listings/_marker.html.erb
<%= image_tag "skimapicon.png", height: 75, width: 75, class: "marker-style", alt: "Logo"%>

app/views/listings/edit.html.erb
<div class="form-container">
  <h1 class="fw-bold pb-2"> Edit your Listing</h1>
  <%= simple_form_for @listing, :html => { :class => "form" }  do |f| %>
    <%= f.input :name, placeholder: "*Title of the post", label: false %>
    <%= f.input :equipment_type, label: false, collection: ["*Equipment Type", "Snowboard", "Helmet", "Gloves", "Skis", "Goggles", "Boots"], selected: "*Equipment Type" %>
    <%= f.input :price_per_day, placeholder: "*Price per day, £", label: false%>
    <%= f.input :photos, as: :file, label: 'Upload Photos', input_html: { multiple: true } %>
    <%= f.input :size, placeholder: "Size", label: false %>
    <%= f.input :condition, label: false, collection: ["Condition", "Brand new", "Excellent", "Very good", "Good", "Well worn"], selected: "Condition"%>
    <%= f.input :brand, placeholder: "Brand", label: false %>
    <%= f.input :gender, label: false, collection: %w[Gender Unisex Men Women Boy Girl], selected: "Gender"%>
    <%= f.input :description%>
    <%= f.submit "Submit listing", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/listings/index.html.erb
<div class="index-container" data-controller="results-filter">
  <div class="d-flex">
    <%= render "filters" %>

    <div class="row container d-flex justify-content-center">
      <div class="listings mt-3">
        <div id="listings">
          <% @listings.each do |listing| %>
            <div data-results-filter-target="result" data-id=<%= listing.id %>>
              <%= link_to listing_path(listing) do %>
                <%= render "listing_card", listing:listing %>
              <% end %>
            </div>
          <% end %>

        </div>
      </div>
    </div>
  </div>
</div>

app/views/listings/new.html.erb
<div class="form-container">
  <h1 class="fw-bold pb-2">  Add new listing!! </h1>
  <%= simple_form_for @listing, :html => { :class => "form" }  do |f| %>
    <%= f.input :name, placeholder: "*Title of the post", label: false %>
    <%= f.input :equipment_type, label: false, collection: ["*Equipment Type", "Snowboard", "Helmet", "Gloves", "Skis", "Goggles", "Boots"], selected: "*Equipment Type" %>
    <%= f.input :price_per_day, placeholder: "*Price per day, £", label: false%>
    <%= f.input :photos, as: :file, label: 'Upload Photos', input_html: { multiple: true } %>
    <%= f.input :size, placeholder: "Size", label: false %>
    <%= f.input :condition, label: false, collection: ["Condition", "Brand new", "Excellent", "Very good", "Good", "Well worn"], selected: "Condition"%>
    <%= f.input :brand, placeholder: "Brand", label: false %>
    <%= f.input :gender, label: false, collection: %w[Gender Unisex Men Women Boy Girl], selected: "Gender"%>
    <%= f.input :description%>
    <%= f.submit "Submit listing", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/listings/show.html.erb
<div class="container justify-content-center">


 <div class="d-flex justify-content-between align-items-center">
    <h1 class="pt-3 pb-3"><%= @listing.name %></h1>
    <p class="m-0"><%= link_to "Back to results", listings_path, class: "back-link" %></p>
  </div>


  <div id="carouselExampleAutoplaying" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-inner">
        <% @listing.photos.each_with_index do |photo, index| %>
          <% if index == 0 %>
            <div class="carousel-item active">
          <% else %>
            <div class="carousel-item">
          <% end %>
            <%= cl_image_tag photo.key, class: "d-block w-100" %>
          </div>
        <% end %>
    </div>
      <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleAutoplaying" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
      </button>
      <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleAutoplaying" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
      </button>
    </div>


    <div class ="prod-info-show row mt-5">
        <div class="description col-6 mr-5">
          <ul class="show-page-list">
            <li class="border-bottom"><strong>Equipment: </strong><%= @listing.equipment_type.capitalize %></li>
            <li class="border-bottom pb-3"><strong>Seller: </strong><%= @listing.user.first_name%> <%= @listing.user.last_name %></li>
            <li><strong>Size: </strong><%= @listing.size %></li>
            <li><strong>Gender: </strong><%= @listing.gender.capitalize %></li>
            <li><strong>Condition: </strong><%= @listing.condition.capitalize %></li>
            <li class="border-bottom pb-3"><strong>Brand: </strong><%= @listing.brand.capitalize %></li>
            <li><strong>Description: </strong></li>
            <li><%= @listing.description %></li>
          </ul>
        </div>


        <div class="booking-form col-6 ml-5<%= "current" if @listing.user == current_user %>">
          <h4>Rent this item</h4>
          <h6> Price Per Day: <strong>£<%= @listing.price_per_day %><strong></h6>
          <%= simple_form_for [@listing, @offer] do |f| %>
            <%= f.input :message %>
            <%= f.input :start_date,
                        as: :string,
                        input_html: { data: { controller: "datepicker" } } %>
            <%= f.input :end_date,
                        as: :string,
                        input_html: { data: { controller: "datepicker" } } %>
            <%= f.submit "Reserve this item", class: "btn btn-primary" %>
          <% end %>
        </div>
    </div>
    <div class="map" style="width: 100%; height: 600px;"
      data-controller="map"
      data-map-markers-value="<%= @markers.to_json %>"
      data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>

  </div>

app/views/offers/_incoming_booking.html.erb
<div class="d-flex justify-content-between border-bottom border-3">
  <p class="m-0"><%= offer.user.first_name %> <%= offer.user.last_name %></p>
  <p class="m-0"><%= offer.start_date %> - <%= offer.end_date %></p>
</div>

app/views/offers/_listing_card.html.erb
<div data-controller="reservation">
  <div class="card-booking listing-card">
    <%= cl_image_tag listing.photos.first.key %>
    <div class="card-booking-infos listing-card">
      <div class="d-flex justify-content-between">
        <h2><%= listing.name %></h2>
        <%= link_to edit_listing_path(listing), class: "back-link" do %>
        <i class="fa-regular fa-pen-to-square"></i>
        <% end %>
      </div>
      <p><%= listing.equipment_type %></p>
      <p><%= link_to "Item details", listing_path(listing), class: "back-link" %></p>
      <%= link_to listing_path(listing), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "back-link delete" do %>
      <i class="fa-regular fa-trash-can"></i>
      <% end %>
    </div>
    <div class="card-booking-dates">
      <h3><%= listing.price_per_day %>£ per day</h3>
      <button class="btn btn-outline-dark reserve" data-action="click->reservation#displayReservations">Reservations</button>
    </div>
  </div>
  <div class="d-none" data-reservation-target="reservations">
    <div class="incoming-card">
      <% if listing.offers.empty? %>
        <p>No reservations for this item yet</p>
      <% else %>
        <% listing.offers.sort_by(&:start_date).each do |offer| %>
          <%= render "incoming_booking", offer:offer %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/offers/_reservation_card.html.erb
<div class="card-booking">
  <%= cl_image_tag offer.listing.photos.first.key %>
  <div class="card-booking-infos">
    <h2><%= offer.listing.name %></h2>
    <p><i class="fa-solid fa-location-dot"></i><strong><%= offer.listing.user.location %></strong></p>
    <% if offer.start_date >= Date.today %>
      <p>Booking confirmed, awating collection.</p>
    <% end %>
    <p id="owner">Owner: <%= "#{offer.listing.user.first_name.capitalize} #{offer.listing.user.last_name.capitalize}" %></p>
  </div>
  <div class="card-booking-dates">
    <h2><%= "#{offer.start_date.day}/#{offer.start_date.mon}/#{offer.start_date.year} - #{offer.end_date.day}/#{offer.end_date.mon}/#{offer.end_date.year}" %></h2>
    <h2 id="price">Total price: £<%= ((offer.end_date - offer.start_date).to_i + 1) * offer.listing.price_per_day %></h2>
  </div>
</div>

app/views/offers/index.html.erb
<div class="bookings-container" data-controller="booking">
  <ul class="list-inline tabs-underlined">
    <li>
      <p class="tab-underlined active" data-action="click->booking#displayBookings" data-booking-target="bookingButton">My Bookings</p>
    </li>
    <li>
      <p class="tab-underlined" data-action="click->booking#displayListings" data-booking-target="listingButton">My Listings</p>
    </li>
  </ul>

  <div data-booking-target="bookings">
    <% @outgoing_offers.each do |offer| %>
      <%= link_to listing_path(offer.listing) do %>
        <%= render "reservation_card", offer:offer %>
      <% end %>
    <% end %>
  </div>
  <div class="d-none" data-booking-target="listings">
    <% @listings.each do |listing| %>
      <%= render "listing_card", listing:listing %>
    <% end %>
  </div>
</div>

app/views/pages/_searchbar.html.erb
<%= form_with url: listings_path, method: :get, class: "d-flex" do |f| %>
  <%= f.text_field :query, id: "search-input", placeholder: "Find ski gear!", class: "form-control bg-white"%>
  <%= f.button nil, class:"nav-link" do %>
    <i class="fa-solid fa-magnifying-glass"></i>
  <% end %>
<% end %>

app/views/pages/home.html.erb
<div class="home-container">
  <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= image_path "Ski-slope-banner-image-1600x393.jpg" %>);">
    <div class="content container">
      <h1>Find the perfect ski equipment for your snowy holiday</h1>
      <p>Buy and sell skiing equipment in your area</p>
      <div class="search-container-banner">
        <%= render "searchbar" %>
      </div>
    </div>
  </div>

  <div id="info-cards" class="info-cards-container">
    <div class="info-card">
      <h3>Browse items</h3>
      <p>Embrace the snow without breaking the bank! Discover and rent your ideal budget-friendly ski gear on our site.</p>
    </div>

    <div class="info-card">
      <h3> Rent items</h3>
      <p>Experience without ownership! Get your hands on rented items for a hassle-free adventure.</p>
    </div>

    <div class="info-card">
      <h3>Lend items</h3>
      <p>Activate your gear's potential! Rent out your unused ski equipment and convert it into cash while it's stored away.</p>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-copyright">
    This website is made by SlopeRentals <i class="fa-regular fa-copyright"></i>
  </div>
  <div class="footer-links">
    <%= link_to "#" do%>
      <i class="fa-solid fa-arrow-up"></i>
    <% end %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon fixed-top">
  <div class="container-fluid">
      <%= link_to root_path, class: "navbar-brand" do %>
        <%= image_tag "Screenshot 2023-11-21 at 12.11.15.png" %>
        <h3>SlopeRentals</h3>
      <% end %>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto d-flex align-items-center">
        <% if user_signed_in? %>
          <li class="nav-item">
            <div class="search-container">
              <%= form_with url: listings_path, method: :get, class: "d-flex" do |f| %>
                <%= f.text_field :query, id: "search-input", placeholder: "Find ski gear!", class: "form-control bg-white rounded-pill"%>
                <%= f.button nil, class:"nav-link" do %>
                  <i class="fa-solid fa-magnifying-glass"></i>
                <% end %>
              <% end %>
            </div>
          </li>
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Browse all", listings_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Make a listing", new_listing_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">

         <% if current_user.photo.key? %>
              <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false%>
           <% else %>
              <%= image_tag "unknown.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false%>
          <% end %>

            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "My Items", offers_path(current_user), class: "dropdown-item" %>
              <%= link_to "Logout", destroy_user_session_path, data: {turbo_method: :delete}, class:"dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item" >
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>